// Centralized courses data with slugs so all pages can reuse consistently
export const courses = [
  { id: 1, title: "AutoCAD Customization", duration: "2 Weeks", students: "156 Students", rating: 4.5, reviews: 124, category: "CAD Customization", description: "Master AutoCAD customization with hands-on projects and real-world applications.", bgGradient: "from-blue-500 to-purple-600", slug: "autocad-customization", price: 500.0 },
  { id: 2, title: "LISP Customization", duration: "3 Weeks", students: "89 Students", rating: 4.3, reviews: 67, category: "CAD Customization", description: "Learn LISP programming for AutoCAD automation and customization.", bgGradient: "from-green-500 to-teal-600", slug: "lisp-customization", price: 400.0 },
  { id: 3, title: "Special Offer on C, C++ & C#", duration: "4 Weeks", students: "234 Students", rating: 4.7, reviews: 189, category: "Programming Languages", description: "Complete programming bundle covering C, C++, and C# fundamentals.", bgGradient: "from-orange-500 to-red-600", slug: "special-offer-c-cpp-csharp", price: 350.0 },
  { id: 4, title: "SolidWorks Customization", duration: "3 Weeks", students: "145 Students", rating: 4.6, reviews: 112, category: "CAD Customization", description: "Advanced SolidWorks customization techniques and API development.", bgGradient: "from-purple-500 to-pink-600", slug: "solidworks-customization", price: 450.0 },
  { id: 5, title: "CATIA Customization", duration: "4 Weeks", students: "98 Students", rating: 4.4, reviews: 76, category: "CAD Customization", description: "Professional CATIA customization and macro development.", bgGradient: "from-indigo-500 to-blue-600", slug: "catia-customization", price: 480.0 },
  { id: 6, title: "NX Customization", duration: "3 Weeks", students: "87 Students", rating: 4.5, reviews: 65, category: "CAD Customization", description: "NX/Unigraphics customization and automation programming.", bgGradient: "from-cyan-500 to-blue-600", slug: "nx-customization", price: 420.0 },
  { id: 7, title: "SolidEdge Customization", duration: "2 Weeks", students: "76 Students", rating: 4.3, reviews: 54, category: "CAD Customization", description: "SolidEdge API programming and customization techniques.", bgGradient: "from-teal-500 to-green-600", slug: "solidedge-customization", price: 390.0 },
  { id: 8, title: "Revit Customization", duration: "3 Weeks", students: "123 Students", rating: 4.6, reviews: 98, category: "CAD Customization", description: "Revit API development and BIM customization solutions.", bgGradient: "from-yellow-500 to-orange-600", slug: "revit-customization", price: 460.0 },
  { id: 9, title: "C, C++ With DSA", duration: "6 Weeks", students: "312 Students", rating: 4.8, reviews: 267, category: "Programming Languages", description: "Complete C/C++ programming with Data Structures and Algorithms.", bgGradient: "from-red-500 to-pink-600", slug: "c-cpp-with-dsa", price: 300.0 },
  { id: 10, title: "Python With DSA", duration: "5 Weeks", students: "289 Students", rating: 4.7, reviews: 234, category: "Programming Languages", description: "Python programming fundamentals with advanced DSA concepts.", bgGradient: "from-green-500 to-blue-600", slug: "python-with-dsa", price: 320.0 },
  { id: 11, title: "C# With DSA", duration: "5 Weeks", students: "198 Students", rating: 4.6, reviews: 156, category: "Programming Languages", description: "C# programming with comprehensive Data Structures coverage.", bgGradient: "from-purple-500 to-indigo-600", slug: "csharp-with-dsa", price: 320.0 },
  { id: 12, title: "Java - JavaScript With DSA", duration: "6 Weeks", students: "345 Students", rating: 4.8, reviews: 298, category: "Programming Languages", description: "Dual language mastery: Java and JavaScript with DSA.", bgGradient: "from-orange-500 to-red-600", slug: "java-javascript-with-dsa", price: 340.0 },
  { id: 13, title: "Full Stack Development", duration: "8 Weeks", students: "267 Students", rating: 4.9, reviews: 223, category: "Software Development", description: "Complete full-stack web development with modern frameworks.", bgGradient: "from-blue-500 to-purple-600", slug: "full-stack-development", price: 600.0 },
  { id: 14, title: "DevOps And Cloud Computing", duration: "6 Weeks", students: "189 Students", rating: 4.7, reviews: 145, category: "Software Development", description: "Modern DevOps practices and cloud computing fundamentals.", bgGradient: "from-cyan-500 to-blue-600", slug: "devops-cloud-computing", price: 550.0 },
  { id: 15, title: "Manual Testing", duration: "4 Weeks", students: "156 Students", rating: 4.5, reviews: 123, category: "Software Testing", description: "Comprehensive manual testing methodologies and best practices.", bgGradient: "from-green-500 to-teal-600", slug: "manual-testing", price: 280.0 },
  { id: 16, title: "Automation Testing", duration: "5 Weeks", students: "134 Students", rating: 4.6, reviews: 108, category: "Software Testing", description: "Advanced automation testing with Selenium and modern tools.", bgGradient: "from-indigo-500 to-purple-600", slug: "automation-testing", price: 330.0 },
];

export function getCourseBySlug(slug) {
  return courses.find((c) => c.slug === slug);
}


